{% set version = "1.1.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-common
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/common_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/common/common_{{ version }}.tar.gz
  sha256: 50d0f4e4aa95b58397750f3de7699746f2a2f3624dd00d5933f06ab5662483fe

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-this.path
  run:
    - r-base
    - r-this.path

test:
  commands:
    - $R -e "library('common')"           # [not win]
    - "\"%R%\" -e \"library('common')\""  # [win]

about:
  home: https://common.r-sassy.org
  dev_url: https://github.com/dbosak01/common/
  license: CC0-1.0
  summary: Contains functions for solving commonly encountered problems while programming in R. This package is intended to provide a lightweight supplement to Base R, and will be useful for almost any R user.
  license_family: CC
  license_file: LICENSE-CC0

extra:
  recipe-maintainers:
    - conda-forge/r
